version: '3'

services:
  golang:
    container_name: "golang"
    restart: always
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - DATABASE_DRIVER=mssql
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=MyStrongPassword!
    depends_on:
      - mssql
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: "mssql"
    command: /bin/sh -c "(/opt/mssql/bin/sqlservr &) && sleep 10s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MyStrongPassword! -d master -Q 'CREATE DATABASE [digitalmarket]' && sleep infinity"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'MyStrongPassword!'
    ports:
      - '1433:1433'
    logging:
      driver: none
    volumes:
      - mssqldata:/var/opt/mssql/data
      - mssqlsecrets:/var/opt/mssql/secrets
      - mssqllog:/var/opt/mssql/log

volumes:
  mssqldata:
  mssqlsecrets:
  mssqllog: